  
---
## Playbook to get system time and append it to backup files

# - hosts: localhost
#   tasks:

#   - set_fact:
#       path: "{{ playbook_dir }}/isg-configs"

#   - name: ENSURE DIR EXISTS - IOS
#     file:
#       path: "{{ path }}"
#       state: "directory"

#   - template:
#       src: mgmisg.j2
#       dest: "{{ path }}/{{ inventory_hostname }}.txt"





- name: Apply  standard ISG template
  hosts: "{{ isg_location }}"
  vars_files:
    - ./creds/default.yml
    - ./vars/main.yml

  # collections:
  #   - cisco.ios
  # gather_facts: no
  # vars:
    # csvfile: "{{ lookup('file', './csv-files/interfaces.csv') }}"
    # erase: false

  tasks:

  # - name: Apply standard router template
  #   ios_config:
  #     src: "./templates/isg_ios.j2"
  #   # when: not erase

  - name: Apply standard router template
    ios_config:
      lines:
        - "service-policy type control {{ item.value.rules }}"
        - "ip address {{ item.value.ip }} {{ item.value.netmask }}"
      parents: "interface TenGigabitEthernet0/0/0.{{ item.key }}"
      # save_when: modified
    with_dict: "{{ interface }}"
    when: ansible_network_os == 'ios'


  - name: Clear Subscriber sessions for VLANS in list
    ios_command:
      commands:
        - "clear subscriber session identifier nas-port vlan {{ item.key }}"
    with_dict: "{{ interface }}"
    tags: [ 'clear_sessions', 'never', ]

  - name: Clear Subscriber sessions  ALL 
    ios_command:
      commands:
        - "clear subscriber session identifier vlan 1170"
    with_dict: "{{ interface }}"
    tags: [ 'clear_sessions_all', 'never', ]

  - name: Add /edit Banner
    ios_banner:
      banner: login
      text: |
        __________________________ WARNING NOTICE ____________________________
        !!!!!! UNAUTHORIZED ACCESS TO THIS NETWORK DEVICE IS PROHIBITED !!!!!!
        You must have explicit permission to access or configure this device.
        This system is for the use of authorized users only. There is no right
        to privacy on this device. Use of this system shall constitute consent
        to monitoring. All activities performed on this device will be logged,
        and violations of this policy may result in disciplinary action,
        and may be reported to law enforcement. In the course of monitoring
        individuals improperly using this system, or in the course of system
        maintenance, the activities of authorized users may also be monitored.
        Anyone using this system expressly consents to such monitoring and is
        advised that if such monitoring reveals possible evidence of criminal
        activity, system personnel may provide the evidence of such monitoring
        to law enforcement officials..
        ______________________________________________________________________
      state: present
    tags: [ 'update_tags' ]



  # - name: Apply standard router template
  #   ios_config:
  #     # provider: "{{ provider_creds }}" 
  #     lines:
  #       - service-policy type control BYPASS
  #       - ip address 10.13.0.2 255.255.128.0
  #   # parents: int gig1/0/11
  #     parents: interface TenGigabitEthernet0/0/0.1170
  #     save_when: modified
  #   # with_dict: "{{ interface }}"


  # - name: DEPLOY ISG CONFIGS
  #   ios_config:
  #     src: "{{ path }}/{{ inventory_hostname }}.txt"
  #     # provider: "{{ provider_creds }}"
  #     host: "{{ ansible_host }}"

