## Ansible Hosts File for Lab 

[CSR_Routers]
mgmisg1 ansible_host=10.0.3.33
mgmisg3 ansible_host=10.0.3.35
nwaisg ansible_host=10.0.112.5
tacisg ansible_host=10.99.99.1
cwsisg ansible_host=10.99.99.9


[nwa]
nwaisg ansible_host=10.0.112.5

[tac]
tacisg ansible_host=10.99.99.1

[cws]
cwsisg ansible_host=10.99.99.9


[mgm]
mgmisg1 ansible_host=10.0.3.33
mgmisg3 ansible_host=10.0.3.35


# [SWITCHES]

# [CSR_VMW_Routers]

# [SWITCHES]

# [NXOS]

# [bigip]

# [WLC]
