## Ansible Hosts File for Lab 

[CSR_Routers]
mgmisg1 ansible_host=10.0.3.33
mgmisg3 ansible_host=10.0.3.35
nwaisg ansible_host=10.0.112.5
tacisg ansible_host=10.99.99.1
cwsisg ansible_host=10.99.99.9

[mgm]
mgmisg1 ansible_host=10.0.3.33
mgmisg3 ansible_host=10.0.3.35


[SWITCHES]
2960 ansible_host=192.168.1.250

[CSR_VMW_Routers]
CSR-11 ansible_host=192.168.106.166

[SWITCHES]
2960 ansible_host=192.168.1.250

[NXOS]
N9K-1 ansible_host=192.168.1.210
N9K-2 ansible_host=192.168.1.211

[bigip]
BIG-IP-1-V ansible_host=192.168.1.180 

[WLC]
WLC-1 ansible_host=192.168.1.231
