# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2




    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0


    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        # Name of the playbook in your workspace.
        playbookName: 
        # Name of the inventory file to use.
        inventoryFile: # optional
        # name of the requirements file to use.
        requirementsFile: # optional
        # If you use private github repositories in your requirements file you need to set galaxyGithubUser and galaxyGithub token.
        galaxyGithubUser: # optional
        # Token to access git source of roles to download. Only needed for private git sources. Github Account needs to be linked to Ansible Galaxy.
        galaxyGithubToken: # optional
        # If inventoryFile is set you can also specify a custom roles path to install your required roles in.
        rolesPath: # optional
        # Keyfile to use for host connections.
        keyFile: # optional
        # Vault Password to decrypt keyFile.
        keyFileVaultPass: # optional
        # String containing all extraVars which you want to be injected into the run.
        extraVars: # optional
        # File containing extra vars.
        extraFile: # optional
        # Choose one of 4 verbosity levels. See Ansible documentation for details.
        verbosity: # optional
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
